In [45]:
import numpy as np
import time

### NP indexes

In [46]:
R = np.random.randint(10, size=(5, 5))
R

array([[7, 4, 7, 7, 5],
       [9, 7, 5, 8, 6],
       [5, 2, 3, 3, 1],
       [6, 5, 3, 2, 4],
       [0, 0, 6, 7, 4]])

In [47]:
# Print first Row
R[0]

array([7, 4, 7, 7, 5])

In [48]:
# Print first Column
R[:,0]

array([7, 9, 5, 6, 0])

In [49]:
type(R[:,0])

numpy.ndarray

In [50]:
R[0,0]

7

In [51]:
#last row
R[-1]

array([0, 0, 6, 7, 4])

In [52]:
#all but last row
R[0:-1]

array([[7, 4, 7, 7, 5],
       [9, 7, 5, 8, 6],
       [5, 2, 3, 3, 1],
       [6, 5, 3, 2, 4]])

In [53]:
#last two Rows
R[-2:]

array([[6, 5, 3, 2, 4],
       [0, 0, 6, 7, 4]])

In [54]:
#last column
R[ : ,-1]

array([5, 6, 1, 4, 4])

In [55]:
#all but last column
R[ : ,0:-1]

array([[7, 4, 7, 7],
       [9, 7, 5, 8],
       [5, 2, 3, 3],
       [6, 5, 3, 2],
       [0, 0, 6, 7]])

In [56]:
#second and third column
R[:,1:3]

array([[4, 7],
       [7, 5],
       [2, 3],
       [5, 3],
       [0, 6]])

### Take care with altering views

In [57]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [58]:
b=a[:2,:2]
b

array([[1, 2],
       [5, 6]])

In [59]:
b[0,0]=77

In [60]:
a

array([[77,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### np.where

In [61]:
a>20

array([[ True, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [62]:
np.where(a > 20 , a*10, a)

array([[770,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12]])

In [63]:
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[7,8,9],[10,11,12]])

In [64]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [65]:
print(np.sum(c))

21


In [66]:
print(np.sum(c, axis=0))

[5 7 9]


In [67]:
print(np.sum(c, axis=1))

[ 6 15]


In [68]:
print(c-d)

[[-6 -6 -6]
 [-6 -6 -6]]


In [69]:
print(np.subtract(c,d))

[[-6 -6 -6]
 [-6 -6 -6]]


### How fast is numpy

In [79]:
#we make a comparison with a big number this time!
#lets try at first with original python/list
start_time = time.time()
count = 100000000 # one million

normalRange = range(count)
print(sum(normalRange))

print("Time taken: %s seconds" % (time.time() - start_time))

4999999950000000
Time taken: 2.661233425140381 seconds


In [80]:
start_time = time.time()
counter = 100000000 # one million

numpyRange = np.arange(counter)
print(numpyRange.sum())

print("Time taken: %s seconds" % (time.time() - start_time))

887459712
Time taken: 0.47808384895324707 seconds


In [81]:
start_time = time.time()
counter = 100000000 # one million
#change data type
numpyRange = np.arange(counter).astype('int64')
print(numpyRange.sum())

print("Time taken: %s seconds" % (time.time() - start_time))

4999999950000000
Time taken: 0.2792038917541504 seconds
